/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EntreprisesSlugRouteImport } from './routes/entreprises.$slug'
import { Route as VehiculesIdRouteImport } from './routes/vehicules.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EntreprisesSlugRoute = EntreprisesSlugRouteImport.update({
  id: '/entreprises/$slug',
  path: '/entreprises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIdRoute = VehiculesIdRouteImport.update({
  id: '/vehicules/$id',
  path: '/vehicules/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/recherche'
    | '/admin'
    | '/entreprises/$slug'
    | '/vehicules/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/recherche'
    | '/admin'
    | '/entreprises/$slug'
    | '/vehicules/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/recherche'
    | '/_authenticated/admin'
    | '/entreprises/$slug'
    | '/vehicules/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RechercheRoute: typeof RechercheRoute
  EntreprisesSlugRoute: typeof EntreprisesSlugRoute
  VehiculesIdRoute: typeof VehiculesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/entreprises/$slug': {
      id: '/entreprises/$slug'
      path: '/entreprises/$slug'
      fullPath: '/entreprises/$slug'
      preLoaderRoute: typeof EntreprisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/$id': {
      id: '/vehicules/$id'
      path: '/vehicules/$id'
      fullPath: '/vehicules/$id'
      preLoaderRoute: typeof VehiculesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RechercheRoute: RechercheRoute,
  EntreprisesSlugRoute: EntreprisesSlugRoute,
  VehiculesIdRoute: VehiculesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
